"""Restaurant archetypes: what kind of place it is, when it is open, what it serves, how it is named.

`core` families are included with high probability, `extra` with lower probability,
`drinks` is a list of (family, how_many) sampled on top. All brand names are invented;
the generator additionally rejects anything on BANNED_NAMES.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Archetype:
    key: str
    label: str                      # shown to the customer, e.g. "Darshini"
    cuisine: str
    count: int                      # target number of restaurants city-wide
    core: tuple[str, ...]
    prefixes: tuple[str, ...]
    suffixes: tuple[str, ...]
    hours: tuple[tuple[str, str, float], ...]   # (open, close, weight); close < open means past midnight
    extra: tuple[str, ...] = ()
    drinks: tuple[tuple[str, int], ...] = ()
    price_levels: tuple[tuple[int, float], ...] = ((2, 1.0),)
    radius: tuple[float, float] = (3.5, 5.5)
    prep: tuple[int, int] = (12, 25)
    menu_size: tuple[int, int] = (18, 36)
    rating_mean: float = 4.1
    tags: tuple[str, ...] = ()


BANNED_NAMES = {
    "mtr", "ctr", "vidyarthi bhavan", "meghana foods", "empire", "truffles", "toit", "third wave coffee",
    "blue tokai", "behrouz biryani", "faasos", "dominos", "domino's", "pizza hut", "starbucks", "chai point",
    "burger king", "mcdonalds", "mcdonald's", "kfc", "subway", "corner house", "brahmin's coffee bar",
    "rameshwaram cafe", "paradise", "bawarma", "bawarchi", "biryani blues", "nandhana", "donne biryani house",
    "chaayos", "cafe coffee day", "ccd", "haldiram's", "bikanervala", "adigas", "kamat", "udupi garden",
    "sagar", "lakeview", "mavalli tiffin rooms", "janatha hotel", "hotel janata",
}

_DAY = (("07:00", "22:00", 0.5), ("08:00", "22:30", 0.3), ("07:30", "21:30", 0.2))
_LUNCH_DINNER = (("11:00", "22:30", 0.5), ("11:30", "23:00", 0.3), ("12:00", "23:30", 0.2))
_ALL_DAY_LATE = (("10:00", "23:30", 0.5), ("11:00", "00:30", 0.3), ("12:00", "01:00", 0.2))

ARCHETYPES: list[Archetype] = [
    Archetype(
        "darshini", "Darshini", "South Indian, Tiffin", 26,
        core=("tiffin",), extra=("ricebowl_south", "meals_light", "chaat"),
        drinks=(("coffee", 2), ("juice", 1)),
        prefixes=("Sri Ganesh", "Shanti", "Amrutha", "Sri Raghavendra", "Kalpavriksha", "Anand", "Maruthi", "Sri Lakshmi",
                  "Namma", "Chethan", "Hosa", "Bhagyalakshmi", "Sri Krishna", "Gowri", "Mahalakshmi", "Sri Venkateshwara",
                  "Vinayaka", "Sri Manjunatha", "Annapurna", "Sri Sai", "Kaveri", "Basava", "Ashwini", "Sri Durga"),
        suffixes=("Darshini", "Tiffins", "Upahara", "Fast Food", "Veg Corner"),
        hours=(("06:30", "22:00", 0.5), ("07:00", "21:30", 0.3), ("06:00", "22:30", 0.2)),
        price_levels=((1, 0.8), (2, 0.2)), radius=(2.5, 4.0), prep=(8, 15), menu_size=(14, 26), rating_mean=4.2,
        tags=("pure-veg", "quick-bites"),
    ),
    Archetype(
        "udupi_tiffin", "Udupi Restaurant", "Udupi, South Indian", 16,
        core=("tiffin", "ricebowl_south", "meals_light"), extra=("meals", "chaat", "sweetshop"),
        drinks=(("coffee", 2), ("juice", 2)),
        prefixes=("Udupi Sri Krishna", "Mangala", "Sri Anantha", "Padmavathi", "Madhuvan", "Kudla", "Sri Gokul", "Surabhi",
                  "Kanaka", "Sri Raghavendra", "Pai's", "Bhat's", "Shetty's", "Nayak's", "Rao's", "Sri Matsyagandha"),
        suffixes=("Bhavan", "Restaurant", "Tiffin Room", "Udupi Cafe", "Vihar"),
        hours=(("07:00", "21:30", 0.6), ("06:30", "22:00", 0.4)),
        price_levels=((1, 0.4), (2, 0.6)), radius=(3.0, 5.0), prep=(10, 18), menu_size=(20, 34), rating_mean=4.25,
        tags=("pure-veg", "family"),
    ),
    Archetype(
        "breakfast_corner", "Breakfast Corner", "Idli, Dosa, Vada", 12,
        core=("tiffin",), extra=("ricebowl_south",), drinks=(("coffee", 2),),
        prefixes=("Early Bird", "Sunrise", "Subah", "Idli", "Vade", "Dose", "Hosa Day", "Morning", "Thatte", "Benne",
                  "Aroma", "Sri Veerabhadra", "Ganesha", "Rise", "Chutney"),
        suffixes=("Idli Corner", "Tiffin Centre", "Breakfast House", "Dose Camp", "Idli Hub"),
        hours=(("06:00", "11:30", 0.5), ("06:30", "12:00", 0.3), ("06:00", "13:00", 0.2)),
        price_levels=((1, 0.7), (2, 0.3)), radius=(2.0, 3.5), prep=(8, 14), menu_size=(12, 22), rating_mean=4.3,
        tags=("pure-veg", "breakfast-only"),
    ),
    Archetype(
        "karnataka_meals", "Meals Hotel", "Karnataka Meals", 14,
        core=("meals", "ricebowl_south"), extra=("tiffin", "sweetshop"), drinks=(("juice", 2), ("softdrink", 1)),
        prefixes=("Sri Siddhartha", "Oota Style", "Anna", "Oota Mane", "Hasiru", "Halli", "Kaveri Oota", "Sri Basaveshwara",
                  "Malnad", "Dharwad", "Shivamogga", "Davangere", "Sri Chowdeshwari", "Sapthagiri", "Mysuru"),
        suffixes=("Meals", "Oota Hotel", "Khanavali", "Bhojanalaya", "Mess"),
        hours=(("11:00", "16:00", 0.4), ("11:00", "22:00", 0.4), ("11:30", "15:30", 0.2)),
        price_levels=((1, 0.5), (2, 0.5)), radius=(3.0, 5.0), prep=(10, 18), menu_size=(14, 26), rating_mean=4.15,
        tags=("lunch-special", "family"),
    ),
    Archetype(
        "military", "Military Hotel", "Nati Style, Non-Veg Karnataka", 14,
        core=("military",), extra=("biryani", "meals_light", "andhra"), drinks=(("softdrink", 2),),
        prefixes=("Nati", "Sri Hanumantha", "Shivaji", "Annapoorneshwari", "Bheema", "Rathna", "Kodi", "Hotel Raju", "Gundappa",
                  "Veerashaiva", "Mandya", "Channapatna", "Kolar", "Chikkaballapur"),
        suffixes=("Military Hotel", "Nati Mane", "Non-Veg Hotel", "Kodi Mane", "Mutton Stall"),
        hours=(("11:00", "22:30", 0.5), ("12:00", "23:00", 0.3), ("11:30", "22:00", 0.2)),
        price_levels=((1, 0.3), (2, 0.7)), radius=(3.0, 5.0), prep=(18, 30), menu_size=(14, 26), rating_mean=4.2,
        tags=("non-veg", "nati-style"),
    ),
    Archetype(
        "andhra_mess", "Andhra Mess", "Andhra, Telangana", 16,
        core=("andhra",), extra=("biryani", "military", "tiffin"), drinks=(("softdrink", 2), ("juice", 1)),
        prefixes=("Guntur", "Vijayawada", "Godavari", "Ruchi", "Bheemavaram", "Nellore", "Konaseema", "Kakinada", "Rayalaseema",
                  "Sri Venkateswara", "Amaravati", "Ongole", "Hyderabadi", "Spicy Garden"),
        suffixes=("Mess", "Andhra Bhojanam", "Spice Kitchen", "Ruchulu", "Meals Point"),
        hours=(_LUNCH_DINNER),
        price_levels=((1, 0.3), (2, 0.7)), radius=(3.5, 5.5), prep=(15, 28), menu_size=(16, 30), rating_mean=4.2,
        tags=("spicy",),
    ),
    Archetype(
        "kerala_kitchen", "Kerala Kitchen", "Kerala, Malabar", 12,
        core=("kerala",), extra=("tamil", "biryani", "tiffin"), drinks=(("juice", 2), ("softdrink", 1)),
        prefixes=("Malabar", "Kuttanad", "Kochi", "Thrissur", "Kannur", "Alleppey", "Nadan", "Onam", "Backwater", "Coconut Grove",
                  "Chakkara", "Meenakshi", "Kozhikode"),
        suffixes=("Kitchen", "Thattukada", "Meals", "Kerala House", "Cafe"),
        hours=(("08:00", "23:00", 0.5), ("11:00", "23:30", 0.3), ("07:30", "22:30", 0.2)),
        price_levels=((1, 0.2), (2, 0.6), (3, 0.2)), radius=(3.5, 5.5), prep=(15, 25), menu_size=(16, 28), rating_mean=4.25,
        tags=("coastal",),
    ),
    Archetype(
        "coastal_seafood", "Coastal Seafood", "Mangalorean, Seafood", 12,
        core=("coastal",), extra=("kerala", "tiffin", "military"), drinks=(("juice", 2), ("softdrink", 1)),
        prefixes=("Kudla", "Mangalore", "Malpe", "Surathkal", "Bunder", "Ullal", "Karavali", "Tulu", "Sea Breeze", "Netravati",
                  "Panambur", "Kundapur", "Coastal Catch"),
        suffixes=("Seafood", "Fish Land", "Coastal Kitchen", "Tulu Nadu", "Fisherman's Table"),
        hours=(("11:00", "23:00", 0.6), ("11:30", "22:30", 0.4)),
        price_levels=((2, 0.6), (3, 0.4)), radius=(3.5, 6.0), prep=(18, 30), menu_size=(16, 28), rating_mean=4.3,
        tags=("seafood", "coastal"),
    ),
    Archetype(
        "tamil_kitchen", "Chettinad & Madurai", "Tamil, Chettinad", 10,
        core=("tamil",), extra=("biryani", "tiffin", "military"), drinks=(("softdrink", 2), ("juice", 1)),
        prefixes=("Madurai", "Chettinad", "Karaikudi", "Thanjavur", "Kongu", "Nellai", "Sri Meenakshi", "Murugan", "Aachi",
                  "Sivakasi", "Rameswaram", "Kovai"),
        suffixes=("Mess", "Kitchen", "Parotta Stall", "Biryani and Meals", "Hotel"),
        hours=(("11:00", "23:30", 0.5), ("12:00", "00:30", 0.3), ("11:30", "23:00", 0.2)),
        price_levels=((1, 0.3), (2, 0.7)), radius=(3.5, 5.5), prep=(15, 25), menu_size=(14, 26), rating_mean=4.15,
        tags=("spicy",),
    ),
    Archetype(
        "biryani_house", "Biryani House", "Biryani, Hyderabadi", 26,
        core=("biryani",), extra=("mughlai", "chinese", "latenight"), drinks=(("softdrink", 2), ("juice", 1)),
        prefixes=("Dum", "Nizami", "Charminar", "Golconda", "Deccan", "Hyderabad", "Awadhi", "Nawab", "Zaika",
                  "Handi", "Royal Dum", "Pot", "Saffron", "Mughal Dastarkhwan", "Ambur", "Kolkata", "Lucknow Darbar"),
        suffixes=("Biryani House", "Dum Biryani", "Biryani Centre", "Biryani Co", "Handi Biryani", "Biryani Point"),
        hours=(_ALL_DAY_LATE),
        price_levels=((1, 0.2), (2, 0.6), (3, 0.2)), radius=(4.0, 6.5), prep=(20, 35), menu_size=(14, 28), rating_mean=4.15,
        tags=("biryani", "bestseller-area"),
    ),
    Archetype(
        "north_dhaba", "North Indian", "North Indian, Punjabi", 22,
        core=("north",), extra=("tandoor", "chinese", "dessert"), drinks=(("juice", 2), ("softdrink", 2)),
        prefixes=("Punjabi", "Amritsari", "Pind", "Dhaba", "Sher-e-Punjab", "Tadka", "Rasoi", "Lajawab", "Delhi", "Chandni Chowk",
                  "Ludhiana", "Khalsa", "Moti Darbar", "Kesar", "Jalandhar", "Patiala", "Chulha"),
        suffixes=("Dhaba", "Rasoi", "Kitchen", "Darbar", "Tadka", "Family Restaurant"),
        hours=(_LUNCH_DINNER),
        price_levels=((1, 0.2), (2, 0.5), (3, 0.3)), radius=(4.0, 6.0), prep=(18, 30), menu_size=(22, 40), rating_mean=4.1,
        tags=("family",),
    ),
    Archetype(
        "mughlai_kebab", "Kebabs & Mughlai", "Mughlai, Tandoor", 14,
        core=("mughlai", "tandoor"), extra=("north", "biryani"), drinks=(("softdrink", 2), ("juice", 1), ("dessert", 2)),
        prefixes=("Shahenshah", "Mughal", "Kebab Factory", "Lucknowi", "Kakori", "Seekh", "Chowk Ke", "Awadh", "Naan",
                  "Peshawar", "Frontier", "Anarkali", "Peshawari", "Zam Zam"),
        suffixes=("Kebabs", "Tandoor", "Grill House", "Darbar", "Kitchen"),
        hours=(("12:00", "23:30", 0.6), ("12:00", "00:30", 0.4)),
        price_levels=((2, 0.5), (3, 0.5)), radius=(4.0, 6.0), prep=(20, 32), menu_size=(20, 34), rating_mean=4.2,
        tags=("non-veg", "grills"),
    ),
    Archetype(
        "chinese_wok", "Indo-Chinese", "Chinese, Indo-Chinese", 22,
        core=("chinese",), extra=("momos", "asian"), drinks=(("softdrink", 2), ("juice", 1)),
        prefixes=("Wok", "Dragon", "Golden", "Lucky", "Hakka", "Szechuan", "Noodle", "Red Lantern", "Chopstick", "Mandarin",
                  "Dynasty", "Jade", "Peking", "Bamboo", "Pagoda", "Tiger Wok", "Oriental"),
        suffixes=("Chinese Kitchen", "Wok House", "Chinese Corner", "Noodles & More", "Garden", "Express"),
        hours=(("11:30", "23:30", 0.5), ("12:00", "00:30", 0.3), ("11:00", "23:00", 0.2)),
        price_levels=((1, 0.3), (2, 0.5), (3, 0.2)), radius=(4.0, 6.0), prep=(15, 25), menu_size=(20, 36), rating_mean=4.05,
        tags=("indo-chinese",),
    ),
    Archetype(
        "momos_tibetan", "Momo Shop", "Tibetan, Momos", 16,
        core=("momos",), extra=("chinese",), drinks=(("softdrink", 2), ("coffee", 1)),
        prefixes=("Himalayan", "Tibet", "Gangtok", "Darjeeling", "Dolma", "Sherpa", "Lhasa", "Kathmandu", "Mount", "Everest",
                  "Yak", "Shillong", "Momo", "Thimphu"),
        suffixes=("Momos", "Momo House", "Kitchen", "Momo Hub", "Dumpling Co", "Corner"),
        hours=(("11:00", "22:30", 0.5), ("12:00", "23:30", 0.3), ("11:30", "23:00", 0.2)),
        price_levels=((1, 0.5), (2, 0.5)), radius=(3.5, 5.5), prep=(12, 20), menu_size=(12, 22), rating_mean=4.1,
        tags=("quick-bites",),
    ),
    Archetype(
        "chaat_corner", "Chaat Corner", "Chaat, Street Food", 14,
        core=("chaat",), extra=("sandwich", "sweetshop", "juice"), drinks=(("juice", 2), ("softdrink", 1)),
        prefixes=("Gully", "Chatpata", "Mumbai", "Delhi", "Bangalore", "VV Puram Style", "Tasty", "Masala", "Chowpatty", "Ram",
                  "Jai Hind", "Sri Vinayaka", "Chat Bandi", "Bombay"),
        suffixes=("Chaat Centre", "Chats", "Chaat Bhandar", "Street Corner", "Snacks"),
        hours=(("15:00", "22:30", 0.5), ("16:00", "23:00", 0.3), ("11:00", "22:00", 0.2)),
        price_levels=((1, 0.8), (2, 0.2)), radius=(2.5, 4.5), prep=(8, 14), menu_size=(12, 24), rating_mean=4.15,
        tags=("pure-veg", "evening-snacks"),
    ),
    Archetype(
        "shawarma_arabian", "Arabian & Shawarma", "Arabian, Shawarma, Grills", 16,
        core=("arabian",), extra=("bbq", "burger"), drinks=(("softdrink", 2), ("juice", 2)),
        prefixes=("Arabian", "Beirut", "Dubai", "Damascus", "Al Safa", "Al Shams", "Shawarma", "Mandi", "Falafel", "Petra",
                  "Cairo", "Istanbul", "Sultan", "Oasis", "Aleppo"),
        suffixes=("Shawarma", "Arabian Kitchen", "Grill and Mandi", "Express", "House", "Nights"),
        hours=(("12:00", "00:30", 0.5), ("13:00", "01:00", 0.3), ("12:00", "23:30", 0.2)),
        price_levels=((1, 0.2), (2, 0.6), (3, 0.2)), radius=(4.0, 6.0), prep=(12, 25), menu_size=(14, 24), rating_mean=4.1,
        tags=("late-night",),
    ),
    Archetype(
        "pizzeria", "Pizzeria", "Pizza, Italian", 14,
        core=("pizza",), extra=("cafe_kitchen", "burger"), drinks=(("softdrink", 2), ("dessert", 2)),
        prefixes=("Crust Theory", "Slice Society", "Oven Story", "Wood Fire", "Dough Lab", "Mozz", "Napoli", "Cheesy Tales", "Base",
                  "Crust and Co", "Little Italy", "Basil and Dough", "Pizza Pie", "Fire and Slice"),
        suffixes=("Pizzeria", "Pizza Kitchen", "Pizza Co", "Oven", "Pizza House"),
        hours=(("11:00", "23:30", 0.5), ("12:00", "00:00", 0.3), ("11:30", "23:00", 0.2)),
        price_levels=((2, 0.5), (3, 0.5)), radius=(4.0, 6.5), prep=(18, 30), menu_size=(14, 22), rating_mean=4.1,
        tags=("kids-fav",),
    ),
    Archetype(
        "burger_joint", "Burger Joint", "Burgers, Fast Food", 14,
        core=("burger",), extra=("pizza", "arabian"), drinks=(("juice", 1), ("dessert", 2)),
        prefixes=("Patty", "Bun", "Smash", "Stack", "Grill Lab", "Burger Barn", "Big Bite", "Juicy", "Toasted", "Meat and Bun",
                  "Cheesy", "Fry Day", "The Burger", "Crunch"),
        suffixes=("Burgers", "Burger Co", "Burger Lab", "Burger House", "Grill"),
        hours=(_ALL_DAY_LATE),
        price_levels=((1, 0.3), (2, 0.5), (3, 0.2)), radius=(4.0, 6.5), prep=(10, 20), menu_size=(14, 24), rating_mean=4.05,
        tags=("kids-fav", "quick-bites"),
    ),
    Archetype(
        "cafe_kitchen", "Cafe & Kitchen", "Continental, Cafe", 16,
        core=("cafe_kitchen",), extra=("coffee", "dessert", "sandwich", "pizza"), drinks=(("coffee", 4),),
        prefixes=("Brew and Bite", "The Daily", "Slow Pour", "Garden", "Roast", "Loft", "Social", "Bluebird", "Pause", "Kettle",
                  "The Reading Room", "Sunday", "Bean There", "Terrace", "The Corner", "Greenhouse", "Studio"),
        suffixes=("Cafe", "Kitchen Table", "Bistro", "Cafe and Kitchen", "Cafe Co"),
        hours=(("08:00", "23:00", 0.5), ("09:00", "23:30", 0.3), ("08:30", "22:30", 0.2)),
        price_levels=((2, 0.5), (3, 0.5)), radius=(4.0, 6.0), prep=(15, 25), menu_size=(22, 36), rating_mean=4.25,
        tags=("work-friendly",),
    ),
    Archetype(
        "coffee_bar", "Coffee Bar", "Coffee, Beverages", 16,
        core=("coffee",), extra=("bakery", "sandwich", "dessert"),
        prefixes=("Kaapi", "Pour Over", "Roastery", "Beans", "Filter Kaapi", "Cup", "Fourth Corner", "Brew Lab", "Mocha", "Decoction",
                  "Davara", "Coorg Estate", "Chikmagalur", "Arabica", "Espresso Room"),
        suffixes=("Coffee Roasters", "Coffee House", "Kaapi Bar", "Coffee Works", "Cafe"),
        hours=(("07:00", "22:30", 0.5), ("08:00", "23:00", 0.3), ("07:00", "21:30", 0.2)),
        price_levels=((1, 0.2), (2, 0.5), (3, 0.3)), radius=(3.0, 5.0), prep=(6, 12), menu_size=(14, 26), rating_mean=4.3,
        tags=("coffee", "pure-veg"),
    ),
    Archetype(
        "irani_cafe", "Irani Cafe", "Irani Chai, Bakery", 8,
        core=("coffee_irani", "teastall"), extra=("bakery",), drinks=(("softdrink", 1),),
        prefixes=("Cafe Zarin", "Rustom", "Cafe Aban", "Cafe Parsi", "Bombay Irani", "Cafe Jamshed", "Persia", "Cafe Pari",
                  "Old Cafe", "Zoroastrian"),
        suffixes=("Irani Cafe", "Chai House", "Cafe and Bakery"),
        hours=(("07:00", "22:00", 0.6), ("06:30", "21:30", 0.4)),
        price_levels=((1, 0.8), (2, 0.2)), radius=(2.5, 4.0), prep=(6, 12), menu_size=(14, 24), rating_mean=4.2,
        tags=("heritage",),
    ),
    Archetype(
        "tea_stall", "Chai & Snacks", "Tea, Snacks", 12,
        core=("teastall",), extra=("chaat",), drinks=(("softdrink", 1),),
        prefixes=("Chai", "Cutting", "Kulhad", "Adda", "Sulaimani", "Tapri", "Nukkad", "Chaiwala", "Thattu", "Chaha"),
        suffixes=("Chai Adda", "Tea Stall", "Chai Junction", "Tapri", "Tea and Snacks"),
        hours=(("06:00", "22:00", 0.5), ("07:00", "23:00", 0.3), ("16:00", "01:00", 0.2)),
        price_levels=((1, 1.0),), radius=(2.0, 3.5), prep=(5, 10), menu_size=(10, 18), rating_mean=4.1,
        tags=("budget",),
    ),
    Archetype(
        "bakery_patisserie", "Bakery", "Bakery, Cakes", 14,
        core=("bakery",), extra=("teastall", "coffee_irani", "sweetshop"), drinks=(("coffee", 2), ("softdrink", 1)),
        prefixes=("Sweet Oven", "Golden Crust", "Butter Bliss", "Cake Walk", "Fresh Breads", "Baker's Basket", "Rolling Pin",
                  "Sugar and Spice", "Crumbs", "Flour Mill", "Iyengar Style", "Sri Lakshmi", "Whisk"),
        suffixes=("Bakery", "Bake House", "Cakes and Pastries", "Patisserie", "Baking Co"),
        hours=(("07:00", "22:00", 0.5), ("08:00", "22:30", 0.3), ("07:30", "21:30", 0.2)),
        price_levels=((1, 0.4), (2, 0.5), (3, 0.1)), radius=(3.0, 5.0), prep=(5, 12), menu_size=(14, 26), rating_mean=4.2,
        tags=("bakery",),
    ),
    Archetype(
        "juice_bar", "Juice & Shakes", "Juices, Shakes, Lassi", 14,
        core=("juice",), extra=("dessert", "sandwich"), drinks=(("coffee", 1),),
        prefixes=("Fresh Squeeze", "Fruit Basket", "Juice Junction", "Pulp", "Thirst Quencher", "Sugarcane", "Mosambi", "Tropical",
                  "Cool Corner", "Shake It", "Fruity", "Lassi Wala", "Tender Coconut Hub"),
        suffixes=("Juice Centre", "Juice Bar", "Fresh Juice", "Shakes and Lassi", "Fruit Parlour"),
        hours=(("08:00", "22:30", 0.5), ("09:00", "23:00", 0.3), ("10:00", "23:30", 0.2)),
        price_levels=((1, 0.6), (2, 0.4)), radius=(2.5, 4.5), prep=(5, 10), menu_size=(14, 26), rating_mean=4.15,
        tags=("pure-veg", "beverages"),
    ),
    Archetype(
        "dessert_parlour", "Dessert Parlour", "Ice Cream, Desserts", 12,
        core=("dessert",), extra=("juice", "bakery", "coffee"),
        prefixes=("Scoop", "Frozen", "Sweet Tooth", "Cone", "Churn", "Gelato", "Kulfi Wala", "Sundae", "Melt", "Creamery",
                  "Dolce", "Sugar Rush", "Waffle"),
        suffixes=("Ice Creams", "Dessert Parlour", "Creamery", "Scoops", "Dessert Lab"),
        hours=(("12:00", "23:59", 0.4), ("13:00", "00:30", 0.3), ("11:00", "23:00", 0.3)),
        price_levels=((1, 0.2), (2, 0.5), (3, 0.3)), radius=(3.5, 6.0), prep=(5, 12), menu_size=(14, 24), rating_mean=4.3,
        tags=("sweet",),
    ),
    Archetype(
        "sweet_shop", "Sweets & Savouries", "Indian Sweets, Snacks", 10,
        core=("sweetshop",), extra=("chaat", "tiffin"), drinks=(("juice", 1),),
        prefixes=("Sri Krishna", "Jaipur", "Mysore", "Dharwad", "Bikaner", "Madurai", "Gokul", "Sri Ganapathi", "Bengal", "Kanti",
                  "Annapoorna", "Swagat", "Rajasthan"),
        suffixes=("Sweets", "Mithai", "Sweets and Savouries", "Sweet House", "Bhandar"),
        hours=(("09:00", "21:30", 0.5), ("08:30", "22:00", 0.3), ("09:30", "21:00", 0.2)),
        price_levels=((1, 0.3), (2, 0.5), (3, 0.2)), radius=(3.0, 5.0), prep=(5, 10), menu_size=(14, 22), rating_mean=4.3,
        tags=("pure-veg", "festive"),
    ),
    Archetype(
        "healthy_bowls", "Healthy Kitchen", "Healthy, Salads, Bowls", 10,
        core=("healthy",), extra=("cafe_kitchen", "juice"), drinks=(("juice", 2),),
        prefixes=("Green Plate", "Lean", "Bowl Theory", "Fit", "Nourish", "Protein Lab", "Leaf and Grain", "Clean Eats", "Macro",
                  "Sprout", "Wholesome", "Fresh Bowl", "Mindful"),
        suffixes=("Healthy Kitchen", "Salad Co", "Bowls", "Fit Kitchen", "Protein House"),
        hours=(("08:00", "22:00", 0.5), ("07:30", "21:30", 0.3), ("09:00", "22:30", 0.2)),
        price_levels=((2, 0.4), (3, 0.6)), radius=(4.0, 6.5), prep=(12, 20), menu_size=(12, 20), rating_mean=4.3,
        tags=("healthy", "high-protein"),
    ),
    Archetype(
        "sandwich_shop", "Sandwich Shop", "Sandwiches, Snacks", 8,
        core=("sandwich",), extra=("teastall", "juice", "burger"), drinks=(("softdrink", 1), ("coffee", 1)),
        prefixes=("Toasty", "Grill", "Stuffed", "Sandwich Lab", "Between Breads", "Bombay Toast", "Crunch", "Layers", "Bread Talk",
                  "Melt"),
        suffixes=("Sandwiches", "Sandwich Co", "Toast House", "Grill Sandwich"),
        hours=(("08:00", "22:30", 0.5), ("09:00", "23:00", 0.5)),
        price_levels=((1, 0.5), (2, 0.5)), radius=(3.0, 5.0), prep=(8, 15), menu_size=(10, 18), rating_mean=4.05,
        tags=("quick-bites",),
    ),
    Archetype(
        "asian_kitchen", "Pan-Asian", "Asian, Thai, Japanese, Korean", 10,
        core=("asian",), extra=("chinese", "momos"), drinks=(("coffee", 2), ("softdrink", 1)),
        prefixes=("Bangkok", "Seoul", "Tokyo", "Ramen", "Umami", "Sakura", "Bao", "Kimchi", "Lemongrass", "Soy and Sesame",
                  "Hanoi", "Osaka", "Bento"),
        suffixes=("Asian Kitchen", "Noodle Bar", "Ramen House", "Bowl House", "Street Asia"),
        hours=(("12:00", "23:30", 0.6), ("12:00", "22:30", 0.4)),
        price_levels=((2, 0.4), (3, 0.6)), radius=(4.0, 6.5), prep=(15, 25), menu_size=(14, 26), rating_mean=4.2,
        tags=("asian",),
    ),
    Archetype(
        "bbq_grill", "Grill House", "Grills, Barbecue", 8,
        core=("bbq",), extra=("tandoor", "arabian", "cafe_kitchen"), drinks=(("softdrink", 2), ("dessert", 2)),
        prefixes=("Smoke Shack", "Ember", "Charcoal", "Fire Pit", "Barrel", "Flame", "Grill Master", "Hickory", "Pit Stop", "Open Fire"),
        suffixes=("Grill House", "Barbecue Co", "BBQ Kitchen", "Smokery"),
        hours=(("12:00", "23:30", 0.6), ("17:00", "00:00", 0.4)),
        price_levels=((2, 0.3), (3, 0.7)), radius=(4.5, 7.0), prep=(20, 35), menu_size=(12, 22), rating_mean=4.25,
        tags=("grills",),
    ),
    Archetype(
        "homefood_tiffin", "Home Kitchen", "Home Style, North Indian", 12,
        core=("homefood",), extra=("north", "meals_light", "tiffin"), drinks=(("juice", 1),),
        prefixes=("Maa Ka", "Ghar Ka", "Amma's", "Nani's", "Home Plate", "Tiffin Wala", "Annapurna Home", "Dabba", "Mom's",
                  "Rasoi Ghar", "Aaji's", "Atithi", "Lunch Box"),
        suffixes=("Khana", "Kitchen", "Tiffin Service", "Dabba", "Rasoi", "Home Foods"),
        hours=(("10:30", "21:30", 0.5), ("11:00", "22:00", 0.5)),
        price_levels=((1, 0.5), (2, 0.5)), radius=(3.5, 6.0), prep=(15, 25), menu_size=(12, 20), rating_mean=4.25,
        tags=("home-style", "office-lunch"),
    ),
    Archetype(
        "gujarati_rajasthani", "Gujarati & Rajasthani", "Gujarati, Rajasthani", 6,
        core=("gujarati",), extra=("chaat", "sweetshop", "north"), drinks=(("juice", 2),),
        prefixes=("Gujju", "Kathiyawadi", "Rajwadi", "Marwar", "Jodhpur", "Surat", "Ahmedabad", "Kutch", "Jaisalmer", "Udaipur"),
        suffixes=("Thali", "Bhojanalay", "Rasoi", "Dining", "Khana Khazana"),
        hours=(("11:00", "22:30", 0.6), ("11:30", "22:00", 0.4)),
        price_levels=((2, 0.6), (3, 0.4)), radius=(4.0, 6.0), prep=(15, 25), menu_size=(12, 20), rating_mean=4.3,
        tags=("pure-veg", "thali"),
    ),
    Archetype(
        "bengali_kitchen", "Bengali Kitchen", "Bengali, East Indian", 6,
        core=("bengali",), extra=("north", "chinese"), drinks=(("softdrink", 1), ("dessert", 1)),
        prefixes=("Kolkata", "Bhojon Ghar", "Sweet Bengal", "Dakshineswar", "Howrah", "Park Street", "Maachh", "Calcutta", "Shantiniketan",
                  "Gariahat"),
        suffixes=("Kitchen", "Rolls and More", "Bhoj", "Bengal House", "Roll Centre"),
        hours=(("11:00", "22:30", 0.5), ("12:00", "23:30", 0.5)),
        price_levels=((1, 0.4), (2, 0.6)), radius=(4.0, 6.5), prep=(12, 25), menu_size=(12, 20), rating_mean=4.2,
        tags=("rolls",),
    ),
    Archetype(
        "late_night", "Late Night Kitchen", "Biryani, Rolls, Snacks", 14,
        core=("latenight",), extra=("biryani", "arabian", "teastall", "chinese", "tamil"), drinks=(("softdrink", 2),),
        prefixes=("Midnight", "Night Owl", "Moonlight", "Insomnia", "2 AM", "Nocturne", "After Hours", "Dark Side", "Owl", "Night Shift",
                  "Lights Out", "Third Shift", "Late Plate", "Starlit"),
        suffixes=("Kitchen", "Bites", "Biryani and Rolls", "Cravings", "Eats", "Express"),
        hours=(("20:00", "03:00", 0.4), ("21:00", "04:00", 0.3), ("19:00", "02:00", 0.3)),
        price_levels=((1, 0.4), (2, 0.6)), radius=(4.0, 7.0), prep=(12, 25), menu_size=(10, 22), rating_mean=4.05,
        tags=("late-night",),
    ),
]
