"""Street food, cafe, bakery, fast food, drinks, desserts, sweets, healthy, Asian."""
from tools.catalogue_gen.dsl import block

DISHES = []

# ------------------------------------------------------------------- chaat
DISHES += block("Chaat & Street Food", "chaat", [
    ("Pani Puri (6 pcs)", "v", 60, 6, "s", 2, 220, "Crisp puris filled with spiced potato and tangy mint water", "golgappa|puchka|pani poori", "bestseller|street-food"),
    ("Sev Puri (6 pcs)", "v", 70, 6, "s", 1, 280, "Flat puris topped with potato, chutneys and sev", "", "street-food"),
    ("Dahi Puri (6 pcs)", "v", 80, 6, "s", 1, 300, "Puris filled with potato, curd and sweet chutney", "", "street-food"),
    ("Masala Puri", "v", 70, 8, "s", 2, 320, "Bangalore speciality: crushed puris in hot peas gravy with onion and sev", "masala poori|ragda puri", "must-try|street-food"),
    ("Bhel Puri", "v", 60, 5, "s", 1, 260, "Puffed rice with sev, onion, tomato and tamarind chutney", "bhel|bhelpuri", "street-food|light"),
    ("Churumuri", "v", 50, 5, "s", 1, 200, "Bangalore puffed-rice mix with peanuts and masala", "churmuri|jhal muri bangalore", "must-try|street-food|light"),
    ("Pav Bhaji (2 pav)", "v", 140, 12, "sdn", 1, 600, "Buttery mashed-vegetable curry with toasted pav", "bhaji pav", "bestseller|street-food"),
    ("Cheese Pav Bhaji", "v", 180, 12, "sdn", 1, 680, "Pav bhaji topped with grated cheese", "", "kids-fav"),
    ("Vada Pav (2 pcs)", "v", 60, 8, "bs", 2, 380, "Mumbai-style potato fritter in a bun with dry garlic chutney", "wada pav|vada pao", "bestseller|street-food"),
    ("Samosa (2 pcs)", "v", 50, 8, "s", 1, 330, "Crisp pastry stuffed with spiced potato and peas", "aloo samosa", "bestseller"),
    ("Samosa Chaat", "v", 90, 8, "s", 1, 420, "Crushed samosa with chole, curd and chutneys", "", "street-food"),
    ("Kachori with Aloo Sabzi", "v", 80, 10, "bs", 1, 420, "Flaky dal kachori with potato curry", "kachori", ""),
    ("Aloo Tikki Chaat", "v", 100, 10, "s", 1, 380, "Pan-fried potato patties with curd, chole and chutney", "aloo tikki", "street-food"),
    ("Papdi Chaat", "v", 90, 8, "s", 1, 360, "Crisp papdi with potato, chickpeas, curd and chutneys", "", ""),
    ("Dabeli (2 pcs)", "v", 70, 8, "s", 1, 380, "Kutchi spiced potato buns with peanuts and pomegranate", "kutchi dabeli", ""),
    ("Ragda Pattice", "v", 100, 10, "s", 1, 400, "Potato patties in white peas gravy with chutneys", "ragda patties", ""),
    ("Mirchi Bajji (4 pcs)", "v", 60, 10, "s", 2, 340, "Chilli fritters in gram-flour batter", "mirchi bhajji|milagai bajji", "street-food"),
    ("Onion Pakoda", "v", 70, 8, "s", 1, 360, "Crispy onion fritters", "onion bhajji|kanda bhaji|pakora", "bestseller"),
    ("Corn Masala", "v", 70, 6, "s", 1, 200, "Steamed sweet corn tossed with butter and masala", "masala corn|sweet corn chaat", "street-food|light"),
    ("Kodubale (100 g)", "v", 60, 3, "s", 1, 480, "Crunchy ring-shaped spicy rice-flour snack", "kodbale", ""),
    ("Gobi Manchurian Street Style", "v", 110, 10, "s", 2, 410, "Bangalore roadside-style fried cauliflower in red sauce", "", "street-food"),
    ("Egg Bonda", "e", 60, 8, "s", 1, 240, "Boiled egg in spiced gram-flour batter", "", ""),
    ("Mysore Bonda", "v", 60, 8, "s", 0, 300, "Soft fried urad-flour bondas with coconut chutney", "mysore bonda", ""),
    ("Dahi Bhalla", "v", 100, 6, "s", 0, 320, "Lentil dumplings in sweet curd with chutneys", "dahi vada chaat", ""),
    ("Jalebi (100 g)", "v", 50, 5, "bs", 0, 380, "Crisp spirals soaked in saffron syrup", "", "sweet"),
])

# ---------------------------------------------------------- chai stall / irani cafe
DISHES += block("Chai & Snacks", "teastall,coffee_irani", [
    ("Masala Chai", "v", 30, 4, "bsdn", 0, 90, "Strong tea with ginger and cardamom", "chai|tea|adrak chai|ginger tea", "bestseller"),
    ("Irani Chai", "v", 40, 4, "bsdn", 0, 110, "Rich, sweet, reduced-milk Irani tea", "irani tea|iranian chai", "must-try"),
    ("Cutting Chai", "v", 20, 3, "bsdn", 0, 60, "Half-glass of strong chai", "", ""),
    ("Lemon Tea", "v", 30, 3, "bsdn", 0, 50, "Hot black tea with lemon", "", "light"),
    ("Green Tea", "v", 40, 3, "bsdn", 0, 10, "Steeped green tea", "", "healthy|light"),
    ("Bun Maska", "v", 50, 3, "bsn", 0, 280, "Soft sweet bun with butter, to dip in chai", "bun maska|maska bun", "must-try|bestseller"),
    ("Bun Maska with Irani Chai", "v", 85, 4, "bsn", 0, 390, "Classic Irani cafe combo", "", "must-try"),
    ("Khari Biscuit (4 pcs)", "v", 40, 2, "bs", 0, 200, "Flaky puff-pastry biscuits", "khari", ""),
    ("Osmania Biscuit (6 pcs)", "v", 50, 2, "bs", 0, 240, "Sweet-salty Hyderabadi tea biscuits", "osmania", ""),
    ("Bread Omelette", "e", 70, 8, "bsn", 1, 340, "Masala omelette sandwiched in toasted bread", "bread omlet|egg sandwich", "bestseller"),
    ("Half-Boiled Egg (2)", "e", 40, 6, "bn", 0, 140, "Soft-boiled eggs with pepper", "", ""),
    ("Egg Bhurji Pav", "e", 100, 10, "bsdn", 1, 480, "Spicy Indian scrambled eggs with buttered pav", "anda bhurji pav", "bestseller"),
    ("Masala Maggi", "v", 70, 8, "sdn", 1, 340, "Instant noodles cooked with onion, tomato and spices", "maggi|maggie|maggi noodles", "bestseller|comfort"),
    ("Egg Maggi", "e", 90, 8, "sdn", 1, 400, "Masala maggi with scrambled egg", "", "bestseller"),
    ("Cheese Maggi", "v", 100, 8, "sdn", 0, 420, "Maggi loaded with cheese", "", "kids-fav"),
    ("Veg Puff", "v", 30, 3, "bs", 0, 200, "Flaky pastry with spiced vegetable filling", "puff|veg puffs", "bestseller"),
    ("Egg Puff", "e", 35, 3, "bs", 0, 230, "Flaky pastry with masala and boiled egg", "egg puffs", "bestseller"),
    ("Chicken Puff", "n", 45, 3, "bs", 1, 260, "Flaky pastry with spiced chicken filling", "chicken puffs", "bestseller"),
    ("Paneer Puff", "v", 45, 3, "bs", 0, 250, "Flaky pastry with paneer masala", "", ""),
    ("Cream Bun", "v", 40, 2, "bs", 0, 290, "Sweet bun with cream filling", "", ""),
    ("Dilpasand", "v", 45, 2, "bs", 0, 310, "Pastry with sweet coconut and tutti-frutti filling", "dil pasand", "must-try"),
    ("Coconut Bun", "v", 35, 2, "bs", 0, 270, "Soft bun with sweet coconut filling", "", ""),
    ("Chicken Cutlet", "n", 70, 8, "s", 1, 280, "Crumb-fried chicken-potato cutlet", "", ""),
    ("Veg Cutlet", "v", 55, 8, "s", 1, 240, "Crumb-fried vegetable cutlet", "", ""),
])

# --------------------------------------------------------------------- pizza
DISHES += block("Pizzas & Sides", "pizza", [
    ("Margherita Pizza (Medium)", "v", 280, 18, "ldn", 0, 800, "Tomato, mozzarella and basil", "margarita pizza|cheese pizza", "bestseller|kids-fav"),
    ("Farmhouse Pizza (Medium)", "v", 360, 20, "ldn", 0, 900, "Capsicum, onion, tomato and mushroom", "veg pizza|farm house pizza", "bestseller"),
    ("Peppy Paneer Pizza (Medium)", "v", 380, 20, "ldn", 2, 920, "Paneer, capsicum and red paprika", "paneer pizza", ""),
    ("Chicken Tikka Pizza (Medium)", "n", 410, 20, "ldn", 2, 960, "Chicken tikka, onion and green chilli", "tikka pizza", "bestseller"),
    ("Pepperoni Pizza (Medium)", "n", 440, 20, "ldn", 1, 980, "Chicken pepperoni and mozzarella", "pepperoni", ""),
    ("BBQ Chicken Pizza (Medium)", "n", 430, 20, "ldn", 1, 940, "Barbecue chicken, onions and jalapenos", "", ""),
    ("Four Cheese Pizza (Medium)", "v", 450, 20, "ldn", 0, 1050, "Mozzarella, cheddar, parmesan and gouda", "4 cheese pizza", ""),
    ("Veg Supreme Pizza (Medium)", "v", 400, 20, "ldn", 1, 920, "Olives, corn, jalapeno, capsicum and mushrooms", "", ""),
    ("Mexican Green Wave Pizza (Medium)", "v", 390, 20, "ldn", 3, 900, "Jalapeno, capsicum and crunchy onion with Mexican herbs", "", ""),
    ("Garlic Bread (4 pcs)", "v", 130, 10, "sdn", 0, 340, "Toasted baguette with garlic butter", "garlic bread sticks", "bestseller"),
    ("Cheesy Garlic Bread (4 pcs)", "v", 170, 10, "sdn", 0, 420, "Garlic bread baked with mozzarella", "stuffed garlic bread", "kids-fav"),
    ("Pasta Bake (Veg)", "v", 280, 18, "ldn", 1, 640, "Penne baked in white sauce with cheese", "baked pasta", ""),
    ("Chicken Wings Peri Peri (6 pcs)", "n", 240, 15, "sdn", 2, 480, "Spicy peri-peri wings", "", ""),
    ("Cheesy Dip", "v", 30, 2, "sldn", 0, 120, "Warm cheese dip", "", ""),
    ("Choco Lava Cake", "v", 110, 8, "sldn", 0, 320, "Warm chocolate cake with a molten centre", "lava cake|choco lava", "sweet|bestseller"),
    ("Calzone Veg", "v", 260, 18, "ldn", 1, 680, "Folded pizza stuffed with vegetables and cheese", "", ""),
])

# --------------------------------------------------------------------- burgers
DISHES += block("Burgers & Fast Food", "burger", [
    ("Aloo Tikki Burger", "v", 100, 8, "lsdn", 1, 420, "Crisp potato patty burger with mayo and lettuce", "veg burger|aloo burger", "bestseller|kids-fav"),
    ("Veg Cheese Burger", "v", 140, 10, "lsdn", 0, 480, "Veg patty with cheese slice and sauces", "cheese burger veg", ""),
    ("Paneer Tikka Burger", "v", 170, 10, "lsdn", 1, 520, "Paneer patty with tandoori mayo", "paneer burger", ""),
    ("Crispy Chicken Burger", "n", 170, 10, "lsdn", 1, 560, "Crumb-fried chicken fillet burger", "chicken burger|zinger burger", "bestseller"),
    ("Spicy Zinger Burger", "n", 190, 10, "lsdn", 3, 600, "Hot and spicy crispy chicken burger", "zinger", ""),
    ("Double Chicken Cheese Burger", "n", 260, 12, "lsdn", 1, 780, "Two chicken patties with double cheese", "double burger", ""),
    ("Veg Wrap", "v", 130, 8, "lsdn", 1, 400, "Grilled tortilla with veg tikki, salad and mayo", "veg tortilla wrap", ""),
    ("Chicken Wrap", "n", 160, 8, "lsdn", 1, 450, "Grilled tortilla with chicken strips and sauces", "chicken tortilla wrap", ""),
    ("French Fries (Regular)", "v", 90, 8, "sdn", 0, 340, "Golden salted fries", "fries", "bestseller|vegan"),
    ("Peri Peri Fries", "v", 110, 8, "sdn", 2, 360, "Fries dusted with peri-peri seasoning", "", ""),
    ("Cheesy Fries", "v", 130, 8, "sdn", 0, 480, "Fries with warm cheese sauce", "cheese fries", "kids-fav"),
    ("Chicken Nuggets (6 pcs)", "n", 140, 8, "sdn", 0, 300, "Crumb-fried chicken bites with dip", "nuggets", "kids-fav"),
    ("Fried Chicken (2 pcs)", "n", 190, 12, "ldn", 2, 520, "Crispy spiced fried chicken", "chicken legs fried|fried chicken", ""),
    ("Onion Rings", "v", 100, 8, "sdn", 0, 320, "Beer-batter style crispy onion rings", "", ""),
    ("Coke (300 ml)", "v", 40, 1, "lsdn", 0, 130, "Chilled cola", "cola|soft drink|coca cola", ""),
    ("Thums Up (300 ml)", "v", 40, 1, "lsdn", 0, 130, "Chilled strong cola", "thums up|thumbs up", ""),
    ("Sprite (300 ml)", "v", 40, 1, "lsdn", 0, 120, "Chilled lemon-lime soda", "", ""),
    ("Veg Meal Box (Burger, Fries, Coke)", "v", 210, 12, "lsdn", 1, 920, "Veg burger, fries and a drink", "veg combo|burger combo", "bestseller"),
    ("Chicken Meal Box (Burger, Fries, Coke)", "n", 270, 12, "lsdn", 1, 1050, "Chicken burger, fries and a drink", "chicken combo", ""),
])

# --------------------------------------------------------- cafe kitchen / continental
DISHES += block("Cafe Kitchen", "cafe_kitchen", [
    ("Penne Alfredo (Veg)", "v", 290, 18, "ldn", 0, 700, "Penne in white cream sauce with mushrooms and broccoli", "pasta alfredo|white sauce pasta", "bestseller"),
    ("Penne Arrabbiata", "v", 280, 18, "ldn", 2, 580, "Penne in spicy tomato-chilli sauce", "red sauce pasta|arrabiata", ""),
    ("Pesto Pasta", "v", 300, 18, "ldn", 1, 620, "Fusilli in basil pesto and parmesan", "", ""),
    ("Chicken Alfredo Pasta", "n", 340, 18, "ldn", 0, 780, "Creamy pasta with grilled chicken", "", "bestseller"),
    ("Mac and Cheese", "v", 280, 15, "lsdn", 0, 720, "Baked macaroni in cheddar sauce", "mac n cheese", "kids-fav|comfort"),
    ("Veg Lasagna", "v", 340, 22, "ld", 0, 680, "Layers of pasta, spinach-ricotta and tomato sauce", "lasagne", ""),
    ("Mushroom Risotto", "v", 360, 22, "ld", 0, 640, "Creamy arborio rice with mushrooms and parmesan", "", ""),
    ("Bruschetta (4 pcs)", "v", 220, 10, "sd", 0, 280, "Toasted ciabatta with tomato, basil and olive oil", "", "light"),
    ("Caesar Salad (Chicken)", "n", 320, 12, "ld", 0, 420, "Romaine, grilled chicken, parmesan and croutons", "caesar salad", "healthy|high-protein"),
    ("Greek Salad", "v", 280, 10, "ld", 0, 300, "Cucumber, tomato, olives and feta", "", "healthy|light"),
    ("Grilled Veg Sandwich", "v", 190, 10, "bls", 0, 420, "Grilled sandwich with vegetables and cheese", "veg sandwich|veg grilled sandwich", "bestseller"),
    ("Club Sandwich (Chicken)", "n", 280, 12, "lsd", 0, 640, "Triple-decker sandwich with chicken, egg and fries", "club sandwich", ""),
    ("Egg Benedict", "e", 330, 15, "b", 0, 560, "Poached eggs and hollandaise on English muffins", "eggs benedict", ""),
    ("Avocado Toast with Poached Egg", "e", 340, 12, "b", 0, 420, "Sourdough with smashed avocado and poached egg", "avo toast", "healthy"),
    ("Pancakes with Maple Syrup (3 pcs)", "v", 250, 12, "bs", 0, 580, "Fluffy buttermilk pancakes with maple syrup", "pancakes", "sweet|kids-fav"),
    ("Belgian Waffle with Chocolate", "v", 260, 12, "bsn", 0, 640, "Crisp waffle with chocolate sauce", "waffle|waffles", "sweet|bestseller"),
    ("French Toast", "e", 220, 10, "b", 0, 480, "Egg-soaked brioche with honey and berries", "", "sweet"),
    ("Cheese Omelette with Toast", "e", 200, 10, "bl", 0, 420, "Three-egg cheese omelette with buttered toast", "omelette|omelet", "high-protein"),
    ("Shakshuka", "e", 300, 15, "bl", 1, 400, "Eggs poached in spiced tomato-pepper sauce with bread", "", ""),
    ("Fish and Chips", "n", 380, 20, "ld", 0, 820, "Beer-battered basa with fries and tartare", "", ""),
    ("Peri Peri Chicken Bowl", "n", 330, 18, "ld", 2, 640, "Peri-peri chicken, rice, corn and grilled veg", "", ""),
    ("Chicken Steak with Fries", "n", 420, 22, "d", 1, 740, "Pan-seared chicken, pepper sauce and fries", "", ""),
    ("Nachos with Cheese and Salsa", "v", 250, 12, "sdn", 1, 560, "Crisp tortillas with melted cheese, salsa and jalapenos", "nachos", "bestseller"),
    ("Quesadilla (Veg)", "v", 280, 15, "lsd", 1, 600, "Grilled tortilla with cheese, beans and peppers", "", ""),
    ("Burrito Bowl (Chicken)", "n", 330, 18, "ld", 1, 700, "Rice, beans, chicken, salsa, sour cream", "", ""),
    ("Tiramisu", "e", 280, 5, "sdn", 0, 420, "Coffee-soaked sponge with mascarpone cream", "", "sweet"),
    ("New York Cheesecake", "e", 270, 5, "sdn", 0, 480, "Baked cheesecake with berry compote", "cheesecake", "sweet"),
])

# --------------------------------------------------------------------- coffee
DISHES += block("Coffee & Beverages", "coffee", [
    ("Filter Coffee", "v", 35, 4, "bsdn", 0, 90, "Traditional South Indian decoction coffee, frothed in a davara", "filter kaapi|kaapi|degree coffee|south indian coffee", "bestseller|must-try"),
    ("Cappuccino", "v", 140, 6, "bsdn", 0, 120, "Espresso with steamed milk and thick foam", "capuchino", "bestseller"),
    ("Cafe Latte", "v", 150, 6, "bsdn", 0, 150, "Espresso with silky steamed milk", "latte", ""),
    ("Americano", "v", 120, 5, "bsdn", 0, 15, "Espresso topped with hot water", "black coffee", "light"),
    ("Flat White", "v", 160, 6, "bsdn", 0, 130, "Double espresso with velvety microfoam", "", ""),
    ("Mocha", "v", 170, 6, "bsdn", 0, 260, "Espresso, chocolate and steamed milk", "cafe mocha", ""),
    ("Cold Coffee", "v", 150, 6, "lsdn", 0, 260, "Chilled blended coffee with milk and ice cream", "iced coffee|cold coffee with ice cream", "bestseller"),
    ("Cold Brew", "v", 170, 5, "lsdn", 0, 25, "Slow-steeped chilled coffee", "cold brew coffee", "light"),
    ("Iced Latte", "v", 170, 5, "lsdn", 0, 140, "Espresso over ice with cold milk", "", ""),
    ("Hot Chocolate", "v", 170, 6, "bsdn", 0, 320, "Thick Belgian-style hot chocolate", "", "sweet|kids-fav"),
    ("Affogato", "v", 190, 5, "sdn", 0, 240, "Vanilla ice cream drowned in espresso", "", "sweet"),
    ("Masala Chai (Pot)", "v", 120, 6, "bsdn", 0, 250, "A pot of milky masala chai, serves two", "chai pot", ""),
    ("Kashmiri Kahwa", "v", 110, 6, "bsdn", 0, 40, "Saffron-cardamom green tea with almonds", "kahwa", "light"),
    ("Iced Tea (Peach)", "v", 140, 5, "lsdn", 0, 110, "Chilled peach black tea", "peach iced tea|ice tea", ""),
    ("Virgin Mojito", "v", 150, 5, "lsdn", 0, 120, "Mint, lime and soda over crushed ice", "mojito", "bestseller"),
    ("Bubble Tea (Taro)", "v", 190, 6, "lsdn", 0, 320, "Taro milk tea with tapioca pearls", "boba|bubble tea", ""),
])

# ---------------------------------------------------------------- bakery
DISHES += block("Bakery", "bakery", [
    ("Black Forest Pastry", "e", 90, 3, "bsdn", 0, 340, "Chocolate sponge with cherries and cream", "black forest", "sweet|bestseller"),
    ("Pineapple Pastry", "e", 85, 3, "bsdn", 0, 320, "Light sponge with pineapple cream", "", "sweet"),
    ("Chocolate Truffle Pastry", "e", 110, 3, "bsdn", 0, 420, "Dense chocolate ganache pastry", "truffle pastry", "sweet|bestseller"),
    ("Red Velvet Pastry", "e", 130, 3, "bsdn", 0, 380, "Cocoa sponge with cream-cheese frosting", "", "sweet"),
    ("Black Forest Cake (500 g)", "e", 550, 10, "sdn", 0, 1700, "Whole eggfull black forest cake", "birthday cake|black forest cake", "festive"),
    ("Eggless Chocolate Cake (500 g)", "v", 600, 10, "sdn", 0, 1800, "Moist eggless chocolate cake", "eggless cake", "festive"),
    ("Plum Cake (250 g)", "e", 280, 5, "sd", 0, 900, "Rum-free fruit plum cake", "christmas cake|fruit cake", "festive"),
    ("Brownie (Walnut)", "e", 110, 4, "sdn", 0, 360, "Fudgy walnut brownie", "brownie", "sweet|bestseller"),
    ("Chocolate Chip Cookies (4 pcs)", "e", 120, 3, "sdn", 0, 420, "Crisp-edged chewy cookies", "cookies", "kids-fav"),
    ("Butter Croissant", "e", 90, 4, "bs", 0, 270, "Flaky laminated butter croissant", "croissant", ""),
    ("Almond Croissant", "e", 140, 4, "bs", 0, 380, "Croissant with almond cream and flakes", "", ""),
    ("Multigrain Bread (Loaf)", "v", 80, 2, "bl", 0, 540, "Fresh multigrain sandwich loaf", "brown bread", "healthy"),
    ("Sourdough Loaf", "v", 180, 2, "bl", 0, 700, "Naturally leavened sourdough", "sourdough", "vegan"),
    ("Doughnut (Chocolate Glazed)", "e", 80, 3, "bsdn", 0, 300, "Soft ring doughnut with glaze", "donut", "sweet|kids-fav"),
    ("Muffin (Blueberry)", "e", 90, 3, "bsd", 0, 340, "Soft muffin with blueberries", "", ""),
    ("Cupcake (Vanilla)", "e", 70, 3, "sdn", 0, 280, "Soft vanilla cupcake with buttercream", "", "kids-fav"),
    ("Nankhatai (6 pcs)", "v", 60, 2, "bs", 0, 300, "Crumbly cardamom shortbread", "", ""),
    ("Dry Fruit Biscuits (200 g)", "v", 90, 2, "bs", 0, 480, "Butter biscuits with cashew and raisin", "", ""),
    ("Rusk (200 g)", "v", 60, 2, "bs", 0, 320, "Crunchy tea-time rusk", "toast biscuit|rusks", ""),
    ("Banana Walnut Cake Slice", "e", 90, 3, "bsd", 0, 330, "Moist banana cake with walnuts", "banana cake", "sweet"),
    ("Cheese Burst Puff", "v", 60, 4, "bs", 0, 280, "Puff pastry oozing cheese", "", ""),
])

# --------------------------------------------------------------------- juice & shakes
DISHES += block("Juices & Shakes", "juice", [
    ("Sugarcane Juice", "v", 50, 5, "ls", 0, 180, "Freshly pressed sugarcane with lime and ginger", "", "vegan|street-food"),
    ("Fresh Orange Juice", "v", 90, 5, "bls", 0, 160, "Fresh-squeezed oranges, no sugar", "orange juice|mosambi juice", "healthy"),
    ("Watermelon Juice", "v", 70, 4, "ls", 0, 100, "Chilled fresh watermelon", "", "vegan|light"),
    ("Pomegranate Juice", "v", 120, 5, "bls", 0, 190, "Fresh-pressed pomegranate", "", "healthy"),
    ("Pineapple Juice", "v", 80, 4, "ls", 0, 130, "Fresh pineapple juice", "", ""),
    ("Muskmelon Juice", "v", 80, 4, "ls", 0, 110, "Fresh muskmelon juice", "", "light"),
    ("ABC Juice (Apple Beet Carrot)", "v", 110, 5, "bls", 0, 140, "Apple, beetroot and carrot blend", "abc juice", "healthy"),
    ("Mango Shake", "v", 110, 5, "ls", 0, 320, "Thick Alphonso mango milkshake", "mango milkshake", "bestseller|sweet"),
    ("Banana Shake", "v", 100, 5, "bls", 0, 300, "Banana blended with chilled milk", "banana milkshake", ""),
    ("Chikoo Shake", "v", 110, 5, "ls", 0, 310, "Sapota milkshake", "sapota shake|chikku shake", ""),
    ("Avocado Shake", "v", 150, 5, "ls", 0, 360, "Creamy avocado milkshake", "butter fruit shake|avocado milkshake", "healthy"),
    ("Oreo Shake", "v", 140, 5, "lsdn", 0, 480, "Oreo cookies blended with ice cream and milk", "oreo milkshake", "kids-fav|sweet"),
    ("Kitkat Shake", "v", 150, 5, "lsdn", 0, 500, "KitKat chocolate thick shake", "", "sweet"),
    ("Fruit Salad with Ice Cream", "v", 140, 6, "lsdn", 0, 300, "Seasonal fruit salad topped with vanilla ice cream", "fruit salad|ice cream fruit salad", "bestseller"),
    ("Sweet Lassi", "v", 80, 4, "bls", 0, 260, "Thick Punjabi sweet yoghurt drink", "lassi", "bestseller"),
    ("Mango Lassi", "v", 100, 4, "ls", 0, 290, "Yoghurt blended with mango", "", ""),
    ("Salted Lassi", "v", 70, 4, "ls", 0, 130, "Savoury cumin lassi", "namkeen lassi", "light"),
    ("Majjige (Buttermilk)", "v", 40, 3, "ls", 0, 60, "Spiced buttermilk with curry leaves and ginger", "masala chaas|chaas|buttermilk|neer more", "light|must-try"),
    ("Tender Coconut Water", "v", 60, 3, "ls", 0, 60, "Fresh tender coconut water", "elaneer|coconut water", "vegan|light"),
    ("Lime Soda (Sweet and Salt)", "v", 60, 3, "ls", 0, 90, "Fresh lime soda, sweet salted or plain", "nimbu soda|lime soda|fresh lime soda", "bestseller"),
    ("Jaljeera", "v", 50, 3, "ls", 1, 50, "Cumin-mint tangy cooler", "jal jeera", "light"),
    ("Nannari Sarbath", "v", 60, 3, "ls", 0, 100, "Chilled sarsaparilla root cooler with lime", "nannari|sarbath", "light"),
    ("Badam Milk (Hot)", "v", 80, 5, "bsdn", 0, 220, "Warm saffron-almond milk", "badam milk|badam doodh", "comfort"),
    ("Rose Milk", "v", 70, 3, "lsd", 0, 210, "Chilled rose-syrup milk", "", "kids-fav"),
    ("Falooda", "v", 150, 8, "sdn", 0, 480, "Rose-syrup milk with vermicelli, basil seeds and ice cream", "faluda", "sweet|bestseller"),
])

# ------------------------------------------------------------------- ice cream & desserts
DISHES += block("Desserts & Ice Cream", "dessert", [
    ("Hot Chocolate Fudge Sundae", "v", 190, 6, "sdn", 0, 540, "Vanilla ice cream, hot fudge, nuts and cherry", "sundae|hot fudge", "sweet|bestseller"),
    ("Brownie with Ice Cream", "v", 170, 6, "sdn", 0, 520, "Warm walnut brownie with vanilla ice cream", "sizzling brownie|brownie sundae", "sweet|bestseller"),
    ("Death by Chocolate", "v", 220, 8, "sdn", 0, 680, "Chocolate cake, ice cream, fudge and chocolate chips", "dbc", "sweet"),
    ("Butterscotch Ice Cream (2 scoops)", "v", 110, 3, "sdn", 0, 320, "Two scoops with caramel crunch", "", "sweet"),
    ("Vanilla Ice Cream (2 scoops)", "v", 90, 3, "sdn", 0, 270, "Classic vanilla bean", "", "sweet|kids-fav"),
    ("Chocolate Ice Cream (2 scoops)", "v", 100, 3, "sdn", 0, 290, "Rich dark chocolate", "", "sweet|kids-fav"),
    ("Tender Coconut Ice Cream", "v", 110, 3, "sdn", 0, 260, "Ice cream with fresh coconut pieces", "", "sweet|must-try"),
    ("Mango Ice Cream (2 scoops)", "v", 110, 3, "sdn", 0, 280, "Alphonso mango ice cream", "", "sweet"),
    ("Malai Kulfi", "v", 90, 4, "sdn", 0, 260, "Dense cardamom-pistachio kulfi on a stick", "kulfi", "sweet|bestseller"),
    ("Kulfi Falooda", "v", 160, 6, "sdn", 0, 460, "Kulfi on rose vermicelli with basil seeds", "", "sweet"),
    ("Rolled Ice Cream (Oreo)", "v", 190, 8, "sdn", 0, 400, "Freshly rolled Thai-style ice cream", "ice cream roll|rolled ice cream", "sweet"),
    ("Gulab Jamun (2 pcs)", "v", 70, 4, "lsdn", 0, 290, "Warm milk-solid dumplings in syrup", "gulab jamoon|jamun", "sweet|bestseller"),
    ("Gulab Jamun with Ice Cream", "v", 120, 5, "lsdn", 0, 420, "Warm gulab jamun and a scoop of vanilla", "", "sweet"),
    ("Rasmalai (2 pcs)", "v", 110, 4, "lsdn", 0, 300, "Soft cheese patties in saffron milk", "ras malai", "sweet|must-try"),
    ("Gajar Ka Halwa", "v", 110, 8, "lsdn", 0, 380, "Slow-cooked carrot pudding with khoya and nuts", "carrot halwa", "sweet|festive"),
    ("Moong Dal Halwa", "v", 130, 8, "lsdn", 0, 460, "Ghee-rich lentil halwa", "", "sweet|festive"),
    ("Rabri Jalebi", "v", 130, 6, "sdn", 0, 520, "Crisp jalebi with thickened sweet milk", "jalebi rabdi", "sweet"),
    ("Hot Jalebi with Rabdi", "v", 140, 8, "sdn", 0, 530, "Fresh hot jalebi with chilled rabri", "", "sweet"),
    ("Payasam (Semiya)", "v", 90, 6, "lsd", 0, 280, "Vermicelli pudding with cashew and raisin", "semiya payasam|kheer", "sweet|festive"),
    ("Bread Halwa", "v", 90, 6, "sd", 0, 400, "Ghee-fried bread in sweet syrup", "shahi tukda", "sweet"),
    ("Cheesecake Jar", "e", 190, 4, "sdn", 0, 420, "Biscuit-base cheesecake in a jar", "", "sweet"),
    ("Banana Split", "v", 210, 6, "sdn", 0, 520, "Banana, three ice-cream scoops, chocolate and nuts", "", "sweet|kids-fav"),
    ("Waffle with Ice Cream", "v", 230, 10, "sdn", 0, 620, "Hot waffle topped with ice cream and caramel", "", "sweet"),
])

# ------------------------------------------------------------------ sweet shop & savouries
DISHES += block("Sweets & Savouries", "sweetshop", [
    ("Mysore Pak (250 g)", "v", 220, 3, "bsd", 0, 1200, "Ghee-rich gram-flour fudge from Mysuru", "mysore paak", "sweet|must-try|bestseller"),
    ("Dharwad Pedha (250 g)", "v", 210, 3, "bsd", 0, 1100, "Caramelised milk fudge, Dharwad style", "dharwad peda", "sweet|must-try"),
    ("Kaju Katli (250 g)", "v", 340, 3, "bsd", 0, 1150, "Cashew diamond fudge", "kaju barfi|kaju burfi", "sweet|festive"),
    ("Motichoor Laddu (4 pcs)", "v", 130, 3, "bsd", 0, 640, "Tiny gram-flour pearls bound in sugar syrup", "laddoo|motichur laddu", "sweet|festive"),
    ("Besan Laddu (4 pcs)", "v", 140, 3, "bsd", 0, 680, "Roasted gram-flour ghee laddus", "", "sweet"),
    ("Coconut Burfi (250 g)", "v", 190, 3, "bsd", 0, 980, "Soft coconut and milk burfi", "", "sweet"),
    ("Holige (Obbattu) (2 pcs)", "v", 100, 5, "bsd", 0, 520, "Sweet flatbread with chana-jaggery filling", "obbattu|puran poli|bele holige", "sweet|festive|must-try"),
    ("Soan Papdi (250 g)", "v", 170, 3, "bsd", 0, 1000, "Flaky gram-flour sweet", "", "sweet|festive"),
    ("Jangri (200 g)", "v", 140, 3, "bsd", 0, 800, "Crisp sugar-syrup coated lentil spirals", "", "sweet"),
    ("Rasgulla Tin (6 pcs)", "v", 160, 3, "lsd", 0, 600, "Spongy cottage-cheese balls in syrup", "", "sweet"),
    ("Chakli (200 g)", "v", 100, 3, "s", 1, 1000, "Crisp spiral rice-flour murukku", "chakkuli|murukku|chakri", "festive"),
    ("Nippattu (200 g)", "v", 90, 3, "s", 1, 960, "Crispy rice-flour crackers with peanuts", "nippat|thattai", ""),
    ("Karasev Mixture (250 g)", "v", 100, 3, "s", 2, 1300, "Savoury sev, nuts and lentil mix", "mixture|south indian mixture|kara boondi", "bestseller"),
    ("Banana Chips (250 g)", "v", 120, 3, "s", 0, 1250, "Kerala-style coconut-oil banana chips", "nendran chips|kerala chips", "vegan"),
    ("Jackfruit Chips (200 g)", "v", 140, 3, "s", 0, 1100, "Crunchy jackfruit chips", "", "vegan"),
    ("Kodubale (250 g)", "v", 110, 3, "s", 1, 1200, "Crunchy rice-flour rings with chilli and coconut", "", ""),
    ("Sweet Box (Assorted, 500 g)", "v", 480, 5, "bsd", 0, 2200, "Assorted festive sweet box", "gift box|mithai box|festival box", "festive"),
    ("Poha Chivda (200 g)", "v", 80, 3, "s", 1, 880, "Light flattened-rice snack mix", "", "light"),
])

# ----------------------------------------------------------------- healthy
DISHES += block("Healthy & Bowls", "healthy", [
    ("Quinoa Veg Bowl", "v", 280, 15, "ld", 0, 480, "Quinoa, roasted veg, chickpeas and tahini", "quinoa bowl|buddha bowl", "healthy|vegan|high-protein"),
    ("Grilled Chicken Salad Bowl", "n", 320, 15, "ld", 0, 420, "Greens, grilled chicken, cherry tomato and lemon dressing", "chicken salad", "healthy|high-protein"),
    ("Paneer Tikka Protein Bowl", "v", 300, 15, "ld", 1, 520, "Paneer tikka over brown rice with sprouts", "protein bowl veg", "healthy|high-protein"),
    ("Chicken Protein Bowl", "n", 330, 15, "ld", 1, 560, "Grilled chicken, brown rice, egg and greens", "protein bowl", "healthy|high-protein"),
    ("Sprouts Chaat", "v", 120, 6, "bs", 1, 180, "Mixed sprouts with onion, tomato and lime", "sprout salad|sprouts", "healthy|vegan|light"),
    ("Overnight Oats (Berry)", "v", 190, 4, "b", 0, 340, "Oats soaked in almond milk with berries and chia", "oats|oatmeal", "healthy|vegan"),
    ("Smoothie Bowl (Acai Style)", "v", 280, 8, "bs", 0, 360, "Frozen fruit base with granola, banana and seeds", "smoothie bowl", "healthy|vegan"),
    ("Millet Upma", "v", 110, 10, "b", 0, 260, "Foxtail millet upma with vegetables", "", "healthy|vegan|light"),
    ("Oats Idli (3 pcs)", "v", 100, 10, "bs", 0, 220, "Steamed oats-lentil idlis", "", "healthy|light"),
    ("Multigrain Wrap (Veg)", "v", 190, 10, "ls", 0, 340, "Multigrain tortilla with hummus and roasted veg", "", "healthy"),
    ("Egg White Omelette (3 eggs)", "e", 150, 8, "bl", 0, 140, "Fluffy egg-white omelette with spinach", "egg whites|white omelette", "healthy|high-protein"),
    ("Boiled Egg Plate (4)", "e", 80, 8, "bs", 0, 310, "Four boiled eggs with pepper", "", "high-protein"),
    ("Hummus Veggie Sticks", "v", 160, 5, "s", 0, 260, "Carrot, cucumber and celery with hummus", "", "healthy|vegan|light"),
    ("Keto Chicken Bowl", "n", 360, 18, "ld", 0, 500, "Chicken thigh with cauliflower rice and avocado", "keto bowl", "healthy|high-protein"),
    ("Green Detox Smoothie", "v", 190, 5, "bs", 0, 160, "Spinach, apple, cucumber and ginger", "green smoothie", "healthy|vegan|light"),
    ("Whey Protein Shake (Chocolate)", "v", 190, 4, "bsdn", 0, 220, "Chocolate whey blended with milk and banana", "protein shake", "high-protein"),
    ("Jowar Roti with Dal", "v", 150, 12, "ld", 0, 380, "Two sorghum rotis with lentils", "", "healthy"),
])

# ---------------------------------------------------------------- sandwich
DISHES += block("Sandwiches", "sandwich", [
    ("Bombay Masala Toast Sandwich", "v", 110, 8, "bsd", 1, 380, "Grilled toast with potato, beetroot, cucumber and green chutney", "bombay sandwich|masala toast|mumbai sandwich", "bestseller|street-food"),
    ("Cheese Chilli Toast Sandwich", "v", 120, 8, "bsd", 2, 410, "Toasted bread with green chilli and melted cheese", "chilli cheese toast", ""),
    ("Paneer Tikka Sandwich", "v", 150, 10, "bsd", 1, 460, "Grilled sandwich with tandoori paneer", "", ""),
    ("Corn Mayo Sandwich", "v", 130, 8, "bsd", 0, 420, "Sweet corn, mayo and cheese", "", "kids-fav"),
    ("Chicken Tikka Sandwich", "n", 170, 10, "bsd", 1, 480, "Chicken tikka with onions and mint mayo", "", ""),
    ("Egg Mayo Sandwich", "e", 120, 8, "bsd", 0, 400, "Egg salad on toasted bread", "egg sandwich", ""),
    ("Nutella Banana Sandwich", "v", 130, 6, "bsd", 0, 460, "Grilled sandwich with Nutella and banana", "", "sweet|kids-fav"),
    ("Veg Club Sandwich", "v", 170, 10, "lsd", 0, 520, "Triple-decker with veg, cheese and egg-less mayo", "", ""),
])

# --------------------------------------------------------------- pan-asian
DISHES += block("Pan-Asian", "asian", [
    ("Chicken Ramen", "n", 380, 18, "ld", 1, 620, "Rich broth with noodles, chicken and soft egg", "ramen|miso ramen", "bestseller|comfort"),
    ("Veg Ramen", "v", 340, 18, "ld", 1, 520, "Veg broth with noodles, mushrooms and bok choy", "", ""),
    ("Veg Sushi Roll (8 pcs)", "v", 320, 15, "ld", 0, 360, "Cucumber, avocado and carrot maki", "california roll veg|sushi", "light"),
    ("Chicken Katsu Curry Rice", "n", 380, 20, "ld", 1, 780, "Crumb-fried chicken cutlet with Japanese curry and rice", "katsu curry|katsu rice", ""),
    ("Teriyaki Chicken Bowl", "n", 350, 15, "ld", 0, 620, "Glazed chicken, sticky rice and sesame greens", "teriyaki bowl", ""),
    ("Pad Thai (Veg)", "v", 330, 15, "ld", 1, 580, "Rice noodles, tofu, peanuts and tamarind", "", ""),
    ("Pad Thai (Chicken)", "n", 360, 15, "ld", 1, 640, "Rice noodles with chicken, egg and peanuts", "", ""),
    ("Thai Green Curry with Rice (Veg)", "v", 340, 18, "ld", 2, 610, "Coconut-milk green curry with vegetables", "green curry", ""),
    ("Thai Red Curry with Rice (Chicken)", "n", 370, 18, "ld", 3, 680, "Spicy red curry with chicken and basil", "red curry", ""),
    ("Tom Yum Soup (Chicken)", "n", 240, 12, "ld", 2, 160, "Hot and sour lemongrass soup", "tom yum", "light"),
    ("Korean Fried Chicken (6 pcs)", "n", 340, 20, "sdn", 2, 560, "Double-fried chicken glazed in gochujang", "kfc style chicken|korean chicken", "bestseller"),
    ("Kimchi Fried Rice", "e", 310, 15, "ld", 2, 600, "Fried rice with kimchi and fried egg", "", ""),
    ("Bibimbap (Veg)", "v", 340, 18, "ld", 1, 560, "Rice bowl with seasoned veggies, gochujang and sesame", "", ""),
    ("Veg Dimsum (6 pcs)", "v", 220, 12, "sdn", 0, 280, "Steamed veg dumplings with chilli oil", "veg dim sum", ""),
    ("Chicken Dimsum (6 pcs)", "n", 250, 12, "sdn", 0, 320, "Steamed chicken dumplings", "chicken dim sum|siu mai", ""),
    ("Gyoza (Chicken, 6 pcs)", "n", 260, 12, "sdn", 0, 340, "Pan-seared Japanese dumplings", "potstickers", ""),
    ("Bao Bun (Crispy Chicken)", "n", 240, 12, "sdn", 1, 420, "Steamed bao with fried chicken and sauce", "bao", ""),
    ("Miso Soup", "v", 160, 6, "ld", 0, 80, "Tofu and wakame in miso broth", "", "light"),
    ("Spicy Garlic Ramen (Chicken)", "n", 400, 18, "ldn", 3, 680, "Fiery garlic-chilli ramen with chicken", "korean ramyeon|spicy ramen", ""),
])

# --------------------------------------------------------------- late night classics
DISHES += block("Late Night Bites", "latenight", [
    ("Chicken Roll (Late Night)", "n", 140, 10, "n", 2, 480, "Hot chicken kathi roll made fresh after midnight", "", "street-food"),
    ("Egg Biryani Single", "e", 180, 15, "n", 2, 620, "Single-serve egg biryani with raita", "", ""),
    ("Chicken 65 (Half)", "n", 160, 12, "n", 3, 300, "Half-plate crisp spicy chicken bites", "", ""),
    ("Egg Dosa (Late Night)", "e", 100, 10, "n", 1, 330, "Egg dosa with chutney", "", ""),
    ("Parotta Combo (2 + Egg Curry)", "e", 150, 12, "n", 2, 640, "Two parottas with egg curry", "", ""),
    ("Cheese Maggi (Late Night)", "v", 100, 8, "n", 0, 420, "Cheesy masala maggi", "", ""),
    ("Hot Chocolate Brownie Combo", "e", 180, 8, "n", 0, 520, "Brownie with a hot chocolate", "", "sweet"),
    ("Midnight Biryani Box", "n", 220, 15, "n", 3, 700, "Hyderabadi chicken biryani, single box with raita", "", ""),
])

# ------------------------------------------------------------ shared soft drinks
DISHES += block("Beverages", "softdrink", [
    ("Coke (300 ml)", "v", 40, 1, "lsdn", 0, 130, "Chilled cola", "cola|coca cola|soft drink", ""),
    ("Thums Up (300 ml)", "v", 40, 1, "lsdn", 0, 130, "Chilled strong cola", "thums up|thumbs up|soft drink", ""),
    ("Sprite (300 ml)", "v", 40, 1, "lsdn", 0, 120, "Chilled lemon-lime soda", "soft drink", ""),
    ("Masala Soda", "v", 50, 3, "lsdn", 1, 70, "Fizzy soda with chaat masala, lime and black salt", "", "light"),
    ("Mineral Water (1 L)", "v", 25, 1, "bldn", 0, 0, "Packaged drinking water", "water bottle|water", ""),
    ("Fresh Lime Water", "v", 50, 3, "lsdn", 0, 40, "Fresh lime with salt or sugar", "nimbu pani", "light"),
])
